baseURL = '/'
locale = 'zh-cn'
title = '探无止境'
theme = 'PaperMod'

[params]
  description = 'Kubernetes、Docker、Go、Linux、CI/CD、中间件、日志系统等工程学习笔记。'
  author = 'ANY'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'blog'
    name = '博客'
    weight = 10
